# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: employee.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'employee.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x12\rEmployeeProto\"\x06\n\x04void\"4\n\x08\x45mployee\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06salary\x18\x03 \x01(\x02\"7\n\tEmployees\x12*\n\temployees\x18\x01 \x03(\x0b\x32\x17.EmployeeProto.Employee2\xd6\x01\n\x0c\x45mployeeGRPC\x12=\n\x0b\x61\x64\x64\x45mployee\x12\x17.EmployeeProto.Employee\x1a\x13.EmployeeProto.void\"\x00\x12?\n\x0cgetEmployees\x12\x13.EmployeeProto.void\x1a\x18.EmployeeProto.Employees\"\x00\x12\x46\n\x12getEmployeesStream\x12\x13.EmployeeProto.void\x1a\x17.EmployeeProto.Employee\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOID']._serialized_start=33
  _globals['_VOID']._serialized_end=39
  _globals['_EMPLOYEE']._serialized_start=41
  _globals['_EMPLOYEE']._serialized_end=93
  _globals['_EMPLOYEES']._serialized_start=95
  _globals['_EMPLOYEES']._serialized_end=150
  _globals['_EMPLOYEEGRPC']._serialized_start=153
  _globals['_EMPLOYEEGRPC']._serialized_end=367
# @@protoc_insertion_point(module_scope)
