# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import employee_pb2 as employee__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in employee_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmployeeGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addEmployee = channel.unary_unary(
                '/EmployeeProto.EmployeeGRPC/addEmployee',
                request_serializer=employee__pb2.Employee.SerializeToString,
                response_deserializer=employee__pb2.void.FromString,
                _registered_method=True)
        self.getEmployees = channel.unary_unary(
                '/EmployeeProto.EmployeeGRPC/getEmployees',
                request_serializer=employee__pb2.void.SerializeToString,
                response_deserializer=employee__pb2.Employees.FromString,
                _registered_method=True)
        self.getEmployeesStream = channel.unary_stream(
                '/EmployeeProto.EmployeeGRPC/getEmployeesStream',
                request_serializer=employee__pb2.void.SerializeToString,
                response_deserializer=employee__pb2.Employee.FromString,
                _registered_method=True)


class EmployeeGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getEmployeesStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmployeeGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.addEmployee,
                    request_deserializer=employee__pb2.Employee.FromString,
                    response_serializer=employee__pb2.void.SerializeToString,
            ),
            'getEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.getEmployees,
                    request_deserializer=employee__pb2.void.FromString,
                    response_serializer=employee__pb2.Employees.SerializeToString,
            ),
            'getEmployeesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getEmployeesStream,
                    request_deserializer=employee__pb2.void.FromString,
                    response_serializer=employee__pb2.Employee.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EmployeeProto.EmployeeGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EmployeeProto.EmployeeGRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmployeeGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeeProto.EmployeeGRPC/addEmployee',
            employee__pb2.Employee.SerializeToString,
            employee__pb2.void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmployeeProto.EmployeeGRPC/getEmployees',
            employee__pb2.void.SerializeToString,
            employee__pb2.Employees.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getEmployeesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/EmployeeProto.EmployeeGRPC/getEmployeesStream',
            employee__pb2.void.SerializeToString,
            employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
